### PR TITLE
Revert "test2"

### PR DESCRIPTION
**Pull request by VladMusat5**
Reverts robertdmtr/exercises#2

### CODE REVIEW

**Comment by DanielMinzat** [comment]
foarte frumos executat acest cod

**Review by VladMusat5 — COMMENTED** [review]
e lux

**Comment by DanielMinzat** [comment]
:))))

**Review by robertdmtr — APPROVED** [review]

**Review by CostineaDaniel — APPROVED** [review]
ii bun

**Review by NoemiEmi — APPROVED** [review]

**Review by Razvan209 — APPROVED** [review]

**Review by DanielMinzat — COMMENTED** [review]
.

**Review by GabrielxXx123 — COMMENTED** [review]
.

**Pull request merged**
